#Exception is some sort of code which cause your program to terminate
def div(a, b):
    return a/b


print(div(3, 0))

#these Type of things are called exceptions; what exceptions do is that it doesn't allow your code to run further

print('hello')